
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid() AND role = 'admin'
    );
$$;

CREATE TABLE IF NOT EXISTS public.profiles (
    id         UUID        PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name       TEXT        NOT NULL,
    dni        TEXT        NOT NULL,
    role       TEXT        NOT NULL DEFAULT 'client'
                           CHECK (role IN ('client', 'admin')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Índice útil para búsquedas por DNI en el panel de admin
CREATE INDEX IF NOT EXISTS idx_profiles_dni ON public.profiles(dni);

-- RLS: activar seguridad por fila
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Todos los usuarios autenticados pueden leer perfiles
CREATE POLICY "profiles_select_authenticated"
    ON public.profiles FOR SELECT
    USING (auth.role() = 'authenticated');

-- Cada usuario puede editar sólo su propio perfil
CREATE POLICY "profiles_update_own"
    ON public.profiles FOR UPDATE
    USING (auth.uid() = id);

-- Los administradores pueden hacer cualquier operación sobre cualquier perfil

CREATE POLICY "profiles_all_admin"
    ON public.profiles FOR ALL
    USING (public.is_admin());


-- ──────────────────────────────────────────────────────────────────────────────
-- 3. TABLA: INSTRUCTORS
-- ──────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.instructors (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT        NOT NULL UNIQUE,
    role       TEXT        NOT NULL,                          
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.instructors ENABLE ROW LEVEL SECURITY;

-- Lectura pública (incluso usuarios no autenticados pueden ver instructores)
CREATE POLICY "instructors_select_public"
    ON public.instructors FOR SELECT
    USING (true);

-- Sólo administradores pueden crear / editar / eliminar instructores
CREATE POLICY "instructors_all_admin"
    ON public.instructors FOR ALL
    USING (public.is_admin());


-- ──────────────────────────────────────────────────────────────────────────────
-- 3.5. TABLA: BRANCHES (SEDES / LOCALES)
-- ──────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.branches (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT        NOT NULL UNIQUE,
    address    TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.branches ENABLE ROW LEVEL SECURITY;

-- Lectura pública de sedes
CREATE POLICY "branches_select_public"
    ON public.branches FOR SELECT
    USING (true);

-- Sólo administradores gestionan sedes
CREATE POLICY "branches_all_admin"
    ON public.branches FOR ALL
    USING (public.is_admin());


-- ──────────────────────────────────────────────────────────────────────────────
-- 4. TABLA: CLASSES
--    Catálogo de clases de baile del estudio.
-- ──────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.classes (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT          NOT NULL,
    level         TEXT          NOT NULL,                    -- "BEGINNER", "ADVANCED", "OPEN LEVEL", "SPECIAL WORKSHOP"
    level_color   TEXT          NOT NULL,                    -- Hex color para la badge del nivel
    time          TEXT          NOT NULL,                    
    instructor_id BIGINT        REFERENCES public.instructors(id) ON DELETE SET NULL,
    branch_id     BIGINT        REFERENCES public.branches(id) ON DELETE SET NULL,
    theme         TEXT          NOT NULL,                    -- Temática, ej: "Neón Night"
    style         TEXT          NOT NULL,                    -- Estilo, ej: "Salsa", "Reggaetón"
    price         NUMERIC(10,2) NOT NULL,
    duration      TEXT          NOT NULL,                    -- ej: "90 min"
    emoji         TEXT          NOT NULL,                    -- Emoji representativo de la clase
    class_date    DATE          NOT NULL DEFAULT CURRENT_DATE,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_classes_class_date    ON public.classes(class_date);
CREATE INDEX IF NOT EXISTS idx_classes_instructor_id ON public.classes(instructor_id);
CREATE INDEX IF NOT EXISTS idx_classes_style         ON public.classes(style);

ALTER TABLE public.classes ENABLE ROW LEVEL SECURITY;

-- Lectura pública de clases
CREATE POLICY "classes_select_public"
    ON public.classes FOR SELECT
    USING (true);

-- Sólo administradores gestionan clases
CREATE POLICY "classes_all_admin"
    ON public.classes FOR ALL
    USING (public.is_admin());


-- ──────────────────────────────────────────────────────────────────────────────
-- 5. TABLA: RESERVATIONS
--    Una reserva = un cliente ocupa un spot (1-32) en una clase específica.
--    La clave UNIQUE (class_id, spot_number) garantiza que no haya colisiones.
-- ──────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.reservations (
    id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    profile_id   UUID        NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    class_id     BIGINT      NOT NULL REFERENCES public.classes(id) ON DELETE CASCADE,
    spot_number  INTEGER     NOT NULL CHECK (spot_number BETWEEN 1 AND 32),
    phone_yape   TEXT        NOT NULL,
    code_yape    TEXT        NOT NULL,
    status       TEXT        NOT NULL DEFAULT 'confirmed'
                             CHECK (status IN ('pending', 'confirmed', 'cancelled')),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Garantiza que el mismo spot no sea reservado dos veces en la misma clase
    UNIQUE (class_id, spot_number)
);

CREATE INDEX IF NOT EXISTS idx_reservations_profile_id ON public.reservations(profile_id);
CREATE INDEX IF NOT EXISTS idx_reservations_class_id   ON public.reservations(class_id);
CREATE INDEX IF NOT EXISTS idx_reservations_status     ON public.reservations(status);

ALTER TABLE public.reservations ENABLE ROW LEVEL SECURITY;

-- Usuarios autenticados pueden ver qué spots están ocupados en cualquier clase
-- (necesario para renderSpotSelection → getOccupiedSpots)
CREATE POLICY "reservations_select_authenticated"
    ON public.reservations FOR SELECT
    USING (auth.role() = 'authenticated');

-- Un cliente sólo puede crear reservas donde el profile_id sea el suyo
CREATE POLICY "reservations_insert_own"
    ON public.reservations FOR INSERT
    WITH CHECK (auth.uid() = profile_id);

-- Un cliente puede cancelar (borrar) sólo sus propias reservas
CREATE POLICY "reservations_delete_own"
    ON public.reservations FOR DELETE
    USING (auth.uid() = profile_id);

-- Un administrador puede hacer cualquier operación sobre cualquier reserva
CREATE POLICY "reservations_all_admin"
    ON public.reservations FOR ALL
    USING (public.is_admin());


-- ──────────────────────────────────────────────────────────────────────────────
-- 6. TRIGGER: SINCRONIZACIÓN AUTOMÁTICA DE PERFILES
--    Cuando Supabase Auth crea un usuario nuevo, este trigger lee los
--    metadatos del registro (name, dni, role) y crea automáticamente el
--    perfil en public.profiles.
--
--    El frontend envía estos metadatos en auth.signUp({ options: { data: { ... } } })
--    tal como está en js/auth.js → registerUser()
-- ──────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    user_role TEXT;
BEGIN
    -- Sólo acepta 'client' o 'admin'; cualquier otro valor cae a 'client'
    user_role := CASE
        WHEN new.raw_user_meta_data->>'role' IN ('client', 'admin')
        THEN new.raw_user_meta_data->>'role'
        ELSE 'client'
    END;

    INSERT INTO public.profiles (id, name, dni, role)
    VALUES (
        new.id,
        COALESCE(NULLIF(TRIM(new.raw_user_meta_data->>'name'), ''), 'Usuario Registrado'),
        COALESCE(NULLIF(TRIM(new.raw_user_meta_data->>'dni'),  ''), '00000000'),
        user_role
    )
    ON CONFLICT (id) DO NOTHING;   -- evita error si el perfil ya fue creado manualmente

    RETURN NEW;
END;
$$;

-- Enlazar el trigger a auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_new_user();


-- ──────────────────────────────────────────────────────────────────────────────
-- 7. DATOS SEMILLA
--    Instructores y clases de ejemplo. Se usan ON CONFLICT DO NOTHING para
--    poder ejecutar el script más de una vez sin errores.
-- ──────────────────────────────────────────────────────────────────────────────

-- Sedes (Locales)
INSERT INTO public.branches (id, name, address) VALUES
    (1, 'Sede Norte',  'Av. Alfredo Mendiola 3600, Los Olivos'),
    (2, 'Sede Sur',    'Av. Benavides 2100, Miraflores'),
    (3, 'Sede Centro', 'Av. Arequipa 1200, Lima')
ON CONFLICT (name) DO NOTHING;

-- Instructores
INSERT INTO public.instructors (id, name, role) VALUES
    (1, 'Elena Márquez',   'Instructora Principal'),
    (2, 'Carlos Rivera',   'Salsa Pro Coach'),
    (3, 'Sofia Chen',      'Fitness Specialist'),
    (4, 'Marco & Estela',  'International Artists'),
    (5, 'Leo Cruz',        'Urban Specialist')
ON CONFLICT (name) DO NOTHING;

-- Clases de hoy (class_date = CURRENT_DATE para que aparezcan al arrancar)
INSERT INTO public.classes
    (name, level, level_color, time, instructor_id, branch_id, theme, style, price, duration, emoji, class_date)
VALUES
    ('Reggaetón Energy',       'ADVANCED',         '#9b5de5', '19:30', 1, 1, 'Neón Night',       'Reggaetón', 25.00, '90 min',  '🔥', CURRENT_DATE),
    ('Salsa Foundation',       'BEGINNER',         '#00b4d8', '18:00', 2, 2, 'Classic Casino',   'Salsa',     25.00, '60 min',  '💃', CURRENT_DATE),
    ('D-Fit Funcional',        'OPEN LEVEL',       '#2dc653', '07:00', 3, 3, 'Power Beat',       'Funcional', 25.00, '60 min',  '⚡', CURRENT_DATE),
    ('Master Bachata Sensual', 'SPECIAL WORKSHOP', '#f4a261', '21:00', 4, 2, 'Midnight Romance', 'Bachata',   50.00, '120 min', '🌹', CURRENT_DATE),
    ('Urban Core',             'OPEN LEVEL',       '#2dc653', '17:00', 5, 1, 'Street Vibe',      'Urbano',    25.00, '90 min',  '🎤', CURRENT_DATE)
ON CONFLICT DO NOTHING;


-- ──────────────────────────────────────────────────────────────────────────────
-- 8. USUARIO ADMINISTRADOR (OPCIONAL)
--    Crea el admin directamente desde SQL para evitar el flujo de registro.
--    Reemplaza el email y la contraseña antes de ejecutar.
--
--    IMPORTANTE: Supabase ya no permite INSERT directo en auth.users desde el
--    SQL Editor en proyectos nuevos. Usa el Dashboard →  Authentication →
--    Users → "Add user" y luego ejecuta el UPDATE de abajo para darle rol admin.
-- ──────────────────────────────────────────────────────────────────────────────

-- Paso 1: Crear el usuario manualmente desde Authentication → Users en el Dashboard.
--         Email: admin@dancefit.com  |  Password: (la que elijas)
--
-- Paso 2: Una vez creado, copia su UUID del Dashboard y ejecuta:
--
-- UPDATE public.profiles
-- SET role = 'admin'
-- WHERE id = '<UUID-DEL-ADMIN-AQUÍ>';


-- ──────────────────────────────────────────────────────────────────────────────
-- FIN DEL SCRIPT
-- ──────────────────────────────────────────────────────────────────────────────
