-- ==============================================================================
-- DANCEFIT STUDIO - ESQUEMA DE BASE DE DATOS NORMALIZADO
-- Ejecuta este script en el SQL Editor de Supabase (https://supabase.com)
-- ==============================================================================

-- Habilitar extensiones necesarias (como UUID)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. TABLA: PROFILES (Perfiles extendidos conectados a auth.users)
CREATE TABLE public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    dni TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'client' CHECK (role IN ('client', 'admin')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Habilitar Row Level Security (RLS) en profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Crear políticas de acceso para profiles
CREATE POLICY "Permitir que los usuarios lean todos los perfiles"
    ON public.profiles FOR SELECT
    USING (true);

CREATE POLICY "Permitir que los usuarios editen su propio perfil"
    ON public.profiles FOR UPDATE
    USING (auth.uid() = id);

CREATE POLICY "Permitir que los administradores editen cualquier perfil"
    ON public.profiles FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid() AND role = 'admin'
        )
    );


-- 2. TABLA: CLASSES (Catálogo de clases de baile)
CREATE TABLE public.classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    level TEXT NOT NULL,
    level_color TEXT NOT NULL,
    time TEXT NOT NULL,
    instructor TEXT NOT NULL,
    role TEXT NOT NULL,
    theme TEXT NOT NULL,
    style TEXT NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    duration TEXT NOT NULL,
    emoji TEXT NOT NULL,
    class_date DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Habilitar RLS en classes
ALTER TABLE public.classes ENABLE ROW LEVEL SECURITY;

-- Crear políticas de acceso para classes
CREATE POLICY "Permitir lectura pública de clases"
    ON public.classes FOR SELECT
    USING (true);

CREATE POLICY "Permitir escritura completa solo a administradores"
    ON public.classes FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid() AND role = 'admin'
        )
    );


-- 3. TABLA: RESERVATIONS (Reservas de spots de clientes)
CREATE TABLE public.reservations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    class_id BIGINT NOT NULL REFERENCES public.classes(id) ON DELETE CASCADE,
    spot_number INTEGER NOT NULL CHECK (spot_number BETWEEN 1 AND 32),
    phone_yape TEXT NOT NULL,
    code_yape TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'confirmed' CHECK (status IN ('pending', 'confirmed')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- Restricción de integridad: Evitar que reserven el mismo spot en la misma clase
    UNIQUE (class_id, spot_number)
);

-- Habilitar RLS en reservations
ALTER TABLE public.reservations ENABLE ROW LEVEL SECURITY;

-- Crear políticas de acceso para reservations
CREATE POLICY "Permitir que los clientes vean sus propias reservas"
    ON public.reservations FOR SELECT
    USING (auth.uid() = profile_id);

CREATE POLICY "Permitir que los clientes creen sus reservas"
    ON public.reservations FOR INSERT
    WITH CHECK (auth.uid() = profile_id);

CREATE POLICY "Permitir que los administradores vean todas las reservas"
    ON public.reservations FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid() AND role = 'admin'
        )
    );

CREATE POLICY "Permitir que los administradores modifiquen cualquier reserva"
    ON public.reservations FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid() AND role = 'admin'
        )
    );


-- 4. DISPARADOR AUTOMÁTICO (TRIGGER)
-- Sincroniza el perfil de la tabla public.profiles de forma automática al registrarse en auth.users
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, name, dni, role)
    VALUES (
        new.id,
        COALESCE(new.raw_user_meta_data->>'name', 'Usuario Registrado'),
        COALESCE(new.raw_user_meta_data->>'dni', '00000000'),
        'client' -- Rol asignado por defecto a nuevos registros
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Enlazar la función handle_new_user a la tabla auth.users
CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- 5. AGREGAR REGISTROS DE PRUEBA (Opcional - Clases iniciales)
-- Descomenta e inserta estas clases si lo deseas
-- INSERT INTO public.classes (name, level, level_color, time, instructor, role, theme, style, price, duration, emoji, class_date) VALUES
-- ('Reggaetón Energy', 'ADVANCED', '#9b5de5', '19:30', 'Elena Márquez', 'Instructora Principal', 'Neón Night', 'Reggaetón', 25.00, '90 min', '🔥', CURRENT_DATE),
-- ('Salsa Foundation', 'BEGINNER', '#00b4d8', '18:00', 'Carlos Rivera', 'Salsa Pro Coach', 'Classic Casino', 'Salsa', 25.00, '60 min', '💃', CURRENT_DATE),
-- ('D-Fit Funcional', 'OPEN LEVEL', '#2dc653', '07:00', 'Sofia Chen', 'Fitness Specialist', 'Power Beat', 'Funcional', 25.00, '60 min', '⚡', CURRENT_DATE),
-- ('Master Bachata Sensual', 'SPECIAL WORKSHOP', '#f4a261', '21:00', 'Marco & Estela', 'International Artists', 'Midnight Romance', 'Bachata', 50.00, '120 min', '🌹', CURRENT_DATE),
-- ('Urban Core', 'OPEN LEVEL', '#2dc653', '17:00', 'Leo Cruz', 'Urban Specialist', 'Street Vibe', 'Urbano', 25.00, '90 min', '🎤', CURRENT_DATE);
