-- ==============================================================================
-- DANCEFIT STUDIO - ESQUEMA DE BASE DE DATOS NORMALIZADO
-- Ejecuta este script en el SQL Editor de Supabase (https://supabase.com)
-- ==============================================================================

-- Habilitar extensiones necesarias (como UUID)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. TABLA: PROFILES (Perfiles extendidos conectados a auth.users)
CREATE TABLE public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    dni TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'client' CHECK (role IN ('client', 'admin')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Habilitar Row Level Security (RLS) en profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Crear políticas de acceso para profiles
CREATE POLICY "Permitir que los usuarios lean todos los perfiles"
    ON public.profiles FOR SELECT
    USING (true);

CREATE POLICY "Permitir que los usuarios editen su propio perfil"
    ON public.profiles FOR UPDATE
    USING (auth.uid() = id);

CREATE POLICY "Permitir que los administradores editen cualquier perfil"
    ON public.profiles FOR ALL
    USING (
        (auth.jwt() -> 'user_metadata'::text ->> 'role'::text) = 'admin'
    );


-- 2. TABLA: INSTRUCTORS (Instructores de baile)
CREATE TABLE public.instructors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Habilitar RLS en instructors
ALTER TABLE public.instructors ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir lectura pública de instructores"
    ON public.instructors FOR SELECT
    USING (true);

CREATE POLICY "Permitir gestión de instructores solo a administradores"
    ON public.instructors FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid() AND role = 'admin'
        )
    );


-- 3. TABLA: CLASSES (Catálogo de clases de baile)
CREATE TABLE public.classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    level TEXT NOT NULL,
    level_color TEXT NOT NULL,
    time TEXT NOT NULL,
    instructor_id BIGINT REFERENCES public.instructors(id) ON DELETE SET NULL,
    theme TEXT NOT NULL,
    style TEXT NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    duration TEXT NOT NULL,
    emoji TEXT NOT NULL,
    class_date DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Habilitar RLS en classes
ALTER TABLE public.classes ENABLE ROW LEVEL SECURITY;

-- Crear políticas de acceso para classes
CREATE POLICY "Permitir lectura pública de clases"
    ON public.classes FOR SELECT
    USING (true);

CREATE POLICY "Permitir escritura completa solo a administradores"
    ON public.classes FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid() AND role = 'admin'
        )
    );


-- 4. TABLA: RESERVATIONS (Reservas de spots de clientes)
CREATE TABLE public.reservations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    class_id BIGINT NOT NULL REFERENCES public.classes(id) ON DELETE CASCADE,
    spot_number INTEGER NOT NULL CHECK (spot_number BETWEEN 1 AND 32),
    phone_yape TEXT NOT NULL,
    code_yape TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'confirmed' CHECK (status IN ('pending', 'confirmed')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- Restricción de integridad: Evitar que reserven el mismo spot en la misma clase
    UNIQUE (class_id, spot_number)
);

-- Habilitar RLS en reservations
ALTER TABLE public.reservations ENABLE ROW LEVEL SECURITY;

-- Crear políticas de acceso para reservations
CREATE POLICY "Permitir que los usuarios autenticados vean la ocupación de reservas"
    ON public.reservations FOR SELECT
    USING (auth.role() = 'authenticated');

CREATE POLICY "Permitir que los clientes creen sus reservas"
    ON public.reservations FOR INSERT
    WITH CHECK (auth.uid() = profile_id);

CREATE POLICY "Permitir que los clientes eliminen sus propias reservas"
    ON public.reservations FOR DELETE
    USING (auth.uid() = profile_id);

CREATE POLICY "Permitir que los administradores vean todas las reservas"
    ON public.reservations FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid() AND role = 'admin'
        )
    );

CREATE POLICY "Permitir que los administradores modifiquen cualquier reserva"
    ON public.reservations FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid() AND role = 'admin'
        )
    );

-- 5. CREACIÓN DE ÍNDICES DE OPTIMIZACIÓN (Heurística de Eficiencia)
CREATE INDEX IF NOT EXISTS idx_reservations_profile_id ON public.reservations(profile_id);
CREATE INDEX IF NOT EXISTS idx_reservations_class_id ON public.reservations(class_id);
CREATE INDEX IF NOT EXISTS idx_classes_class_date ON public.classes(class_date);


-- 6. DISPARADOR AUTOMÁTICO (TRIGGER)
-- Sincroniza el perfil de la tabla public.profiles de forma automática al registrarse en auth.users
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
    user_role TEXT;
BEGIN
    user_role := CASE
        WHEN new.raw_user_meta_data->>'role' IN ('client', 'admin') THEN new.raw_user_meta_data->>'role'
        ELSE 'client'
    END;

    INSERT INTO public.profiles (id, name, dni, role)
    VALUES (
        new.id,
        COALESCE(new.raw_user_meta_data->>'name', 'Usuario Registrado'),
        COALESCE(new.raw_user_meta_data->>'dni', '00000000'),
        user_role
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Enlazar la función handle_new_user a la tabla auth.users
CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- 7. AGREGAR REGISTROS DE PRUEBA (Semillas)
-- Insertar instructores
INSERT INTO public.instructors (id, name, role) VALUES
(1, 'Elena Márquez', 'Instructora Principal'),
(2, 'Carlos Rivera', 'Salsa Pro Coach'),
(3, 'Sofia Chen', 'Fitness Specialist'),
(4, 'Marco & Estela', 'International Artists'),
(5, 'Leo Cruz', 'Urban Specialist')
ON CONFLICT (name) DO NOTHING;

-- Insertar clases iniciales
INSERT INTO public.classes (name, level, level_color, time, instructor_id, theme, style, price, duration, emoji, class_date) VALUES
('Reggaetón Energy', 'ADVANCED', '#9b5de5', '19:30', 1, 'Neón Night', 'Reggaetón', 25.00, '90 min', '🔥', CURRENT_DATE),
('Salsa Foundation', 'BEGINNER', '#00b4d8', '18:00', 2, 'Classic Casino', 'Salsa', 25.00, '60 min', '💃', CURRENT_DATE),
('D-Fit Funcional', 'OPEN LEVEL', '#2dc653', '07:00', 3, 'Power Beat', 'Funcional', 25.00, '60 min', '⚡', CURRENT_DATE),
('Master Bachata Sensual', 'SPECIAL WORKSHOP', '#f4a261', '21:00', 4, 'Midnight Romance', 'Bachata', 50.00, '120 min', '🌹', CURRENT_DATE),
('Urban Core', 'OPEN LEVEL', '#2dc653', '17:00', 5, 'Street Vibe', 'Urbano', 25.00, '90 min', '🎤', CURRENT_DATE);
